language: python
env:
  - TOXENV=json-py35
  - TOXENV=json-py34
  - TOXENV=ujson-py35
  - TOXENV=ujson-py34
  - TOXENV=pycares-py35
  - TOXENV=tornado43-py35
  - TOXENV=tornado43-py34
  - TOXENV=tornado44-py35
  - TOXENV=tornado44-py34
  - TOXENV=pycares-pypy3
  - TOXENV=pycares-pypy4
  - TOXENV=json-pypy3
  - TOXENV=json-pypy4
  - TOXENV=ujson-pypy3
  - TOXENV=ujson-pypy4
  - TOXENV=tornado43-pypy3
  - TOXENV=tornado43-pypy4
  - TOXENV=tornado44-pypy3
  - TOXENV=tornado44-pypy4

install:
  - pip install tox 
script:
  - tox
  - tox ujson
